### ISSUE TITLE
Publish to nuget

### ISSUE THREAD

**Issue by M-Zuber** [ianlee74/CSharp-Name-Parser#3]
Would you consider publishing this to nuget?

**Comment by ianlee74** [comment]
Mordechai,

Thank you for your interest. It's always good to know someone is finding
your work useful. Unfortunately, I never developed this function to a point
where I was happy with it and I no longer use it. I now use a SQL based
solution for most cases. If you're finding it useful for your needs and
want it on Nuget, then I suggest you fork my repo and publish it yourself.
Of course, if you make any improvements I'd appreciate the contributions.

Thanks!

---

R. Ian Lee, Sr.
LinkedIn:  http://www.linkedin.com/in/rianlee
Blog:  http://ianlee.info http://blog.ianlee.info
Twitter:  @ianlee74 https://twitter.com/ianlee74 and @Gadgeteerin
https://twitter.com/gadgeteerin

Do you have a project you'd like to see published at MAKEzine.com?  Let's
talk!

**Comment by M-Zuber** [comment]
Thank you for the reply, but as of right now I don't have the time to add another project to my maintaining list.
Will keep it in mind though.
